# Generated by Django 3.2.7 on 2021-10-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211015_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
