# Generated by Django 3.2.7 on 2021-10-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_emails_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emails',
        ),
    ]
