# Generated by Django 3.2.7 on 2021-10-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_delete_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('message', models.TextField()),
            ],
        ),
    ]
