# Generated by Django 3.2.7 on 2021-10-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
