# Generated by Django 3.2.7 on 2021-10-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_emails_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='date_time',
        ),
    ]
