# Generated by Django 3.2.7 on 2021-10-16 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_emails_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emails',
        ),
    ]
